trigger:
- main  # Trigger pipeline on changes to the 'main' branch

pool:
  name: 'Default'  # Default pool if your agent is already registered with Azure DevOps
  demands:
    - agent.name == spc  # Specify your custom agent name ('spc')

variables:
  javaVersion: '11'  # Define Java version for consistency
  mavenVersion: '3.8.1'  # Define Maven version (if needed)

jobs:
- job: Build
  displayName: 'Build and Test Java Project'
  steps:

    # Step 1: Checkout the code from GitHub
    - checkout: self  # Default GitHub checkout

    # Step 2: Verify Java and Maven are correctly installed on the custom agent
    - script: java -version
      displayName: 'Verify Java Installation'

    - script: mvn -version
      displayName: 'Verify Maven Installation'

    # Step 3: Build the project using Maven
    - script: mvn clean install -DskipTests
      displayName: 'Maven Build'

    # Step 4: Run tests with Maven
    - script: mvn test
      displayName: 'Run Unit Tests'

    # Step 5: Publish build artifacts (e.g., JAR or WAR file)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/target'
        ArtifactName: 'drop'
        publishLocation: 'Container'
