trigger:
- main  # Trigger the pipeline on changes to the 'main' branch

# Use a hosted agent pool (Azure DevOps provides hosted agents with Java/Maven already installed)
pool:
  vmImage: 'ubuntu-latest'  # You can also use 'windows-latest' or 'macos-latest' depending on your project

variables:
  javaVersion: '17'  # Java version (adjust as needed)
  mavenVersion: '3.9.11'  # Maven version (adjust as needed)

jobs:
- job: Build
  displayName: 'Build and Test Java Project'
  steps:

    # Step 1: Checkout the code from the repository
    - checkout: self  # Checkout the code from the repository

    # Step 2: Verify Java and Maven installations (optional)
    - script: java -version
      displayName: 'Verify Java Installation'

    - script: mvn -version
      displayName: 'Verify Maven Installation'

    # Step 3: Build the project using Maven
    - script: mvn clean install -DskipTests
      displayName: 'Maven Build'

    # Step 4: Run unit tests with Maven
    - script: mvn test
      displayName: 'Run Unit Tests'

    # Step 5: Publish build artifacts (e.g., JAR or WAR file)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/target'
        ArtifactName: 'drop'
        publishLocation: 'Container'
